### ISSUE TITLE
idea: should we gate who can access the pair's oracle

### ISSUE THREAD

**Issue by OliverNChalk** [vexchange/v3-core#101]
MakerDAO whitelists who can call their oracle, this enables them to monetize their oracle avoiding a tragedy of the commons (where everyone relies on an oracle but no one incentivizes its maintenance).

Proposal:

- Add `oracleCaller` role that determines who can call the oracle access methods.
- If we later want to let anyone call we can add a simple `OracleCaller` contract that enables anyone to call.
- If we decide to monetize, we can manually whitelist different protocols once they reach a pricing agreement with management/DAO.

**Comment by xenide** [comment]
Yes agreed that we should implement this at this stage since it'll be baked into the oracle code. 

Will implement in the next few days

**Comment by xenide** [comment]
closed as this is addressed in #112
