### ISSUE TITLE
question: `_getExchangeRate` in AssetManager, any case where this can fail? 

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#115]
Currently it checks if the totalShares are zero, but does not check if the balance of aTokens is zero. 

Through logical deduction, it seems that the AaveManager should not have any aTokens if the total shares are zero. But could there be corner cases where the shares not zero, but the number of aTokens are zero?

**Comment by OliverNChalk** [comment]
Given we track totalSupply and user balances in lockstep, the invariant `sum(user_balances) == total_supply` should hold. This would be an interesting use case of foundry invariant testing. I will try write an invariant test for this

**Comment by OliverNChalk** [comment]
Elected not to write the invariant test due to the amount of time/effort required to wire up Aave correctly for invariant fuzzing
