### ISSUE TITLE
question: is there a problem with using `_totalToken0/1()` for swap

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#116]
The amount managed by the AssetManager might have changed between the last `mint`/`burn`. 

Case 1: If the AssetManager lost some money, the swap will fail if the pair tries to pull assets it thinks it has from the manager. 

Case 2: If the AssetManager gained money, the swapper might get more than what he expected

**Comment by OliverNChalk** [comment]
I think this is wrong, the swapper will not get more/less because of PNL. The PNL _may_ directly change the exchange rate, which indirectly slightly changes the output but it will not change directly the output. Agree?

**Comment by xenide** [comment]
you're right, since on swap the pair is not informed of any loss or gain (no call to `_syncManaged`), swapper will not get more/less. 

There is one case where there could be an issue (case 1 above): 
e.g. there is 100 tokens of TokenA as reserves for the pair. 50 TokenA is managed by the AM. AM loses 10 TokenA. Now pair only has 50+40, but it thinks it has 50+50. A swapper comes along and asks for 95 TokenA as output. Swap will fail as it only has 40, not 50 left to pull. 

There is no way to mitigate this (without syncing with AM which we don't wanna do). We just have to acknowledge that this is an edge case we could face in production. To recover from it, someone just has to call `mint`/`burn`/`sync` so that the pair is informed of the real amount of TokenA it has. Recovery is pretty easy. 

Can close this issue if you acknowledge the above and have no further comments.

**Comment by OliverNChalk** [comment]
I think our goal long-term is to have the AM be insured and make losses "impossible" in our system. The DAO would essentially guarantee your principle back for an insurance fee

**Comment by xenide** [comment]
Okay noted this long term feature goal we have. 

Would it be an opt-in thing for individual users to sign up for this insurance, or would the whole pool be covered by this insurance by default and then the pool pays a small amount to the DAO as the insurance fee?

**Comment by OliverNChalk** [comment]
Whole pool and i dont think the amount they pay will be small

**Comment by xenide** [comment]
Okay noted. 

Closing as the original question has been addressed.
