### ISSUE TITLE
question: are shares still correct when we add/remove underlying tokens if there was a PnL during `adjustManagement`, but the pair has not been informed? 

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#117]
This is referring to AaveManager::shares, and is talking about the same pair. 

Suppose a pair has some assets managed by the AM. Some profit/loss has happened, and then the privileged AM owner decides to invest / divest some assets manually. Because `adjustManagement` does not inform the pair of gains / losses, only changes in managed amount for the current adjustment. Could this result in an inaccurate number of shares as tracked by the asset manager? I'm going to write test cases to show this 

Another test case to add: Pair1 and Pair2 both have USDC managed by the asset manager. Pair1 lets the asset manager manage some of its USDC. Then the asset manager makes some gains / losses on these assets. Then Pair2 comes along and gets some assets managed by the manager. At this point in time are the shares for Pair1 still accurate and the shares issued for Pair2 correct? We already have a test case for profit, so need to add one for the loss case

**Comment by OliverNChalk** [comment]
This should be impossible? There is an invariant that we should always get an accurate PNL before allowing any `mint` or `burn`?
