### ISSUE TITLE
assert: confirm none of our initCode is above 48kb

### ISSUE THREAD

**Issue by OliverNChalk** [vexchange/v3-core#132]
## Details

Shanghai will limit initCode to a maximum of 48kb: https://eips.ethereum.org/EIPS/eip-3860

**Comment by xenide** [comment]
okie... so I guess by the time we deploy onto mainnet, if the chains we are launching on also have upgraded to Shanghai, we just have to drop those commits that dealt with splitting contracts into 2

**Comment by OliverNChalk** [comment]
If we drop those commits then we cannot deploy? Also, this will affect us even if we deploy before Shanghai because our factory will still want to create new pairs

**Comment by OliverNChalk** [comment]
The current size of the `StablePair` initCode is `52567` bytes. This is because it includes the `StableMintBurn` initCode. To address this, what we can do is:

- Store the StableMintBurn initCode in the factory via SSTORE

**Comment by OliverNChalk** [comment]
Closed in 69b35191af4ff09b6616fcf37665769245e56ca7
