### ISSUE TITLE
fix: handle case when amount managed by asset manager exceeds `uint104` 

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#156]
## Potential Solution 1

- if `lToken0/1Managed` exceeds uint104 during `_syncManaged`, we can skim it to the recoverer's address. 

- Pros: 
   - Since the recoverer is a trusted party, the excess foam beyond `uint104` can be safely scooped off and redistributed later. This is similar to the main `skim` function 

- Cons: 
   - accounting might be a pain to compensate people who have exited the pool 

## Potential Solution 2

- can't think of anymore?? 

## Potential Solution 3 
- monitor and manually intervene when it gets near the threshold 

Cons:
- will still overflow and potentially brick the pair

**Comment by OliverNChalk** [comment]
I think the skim approach is pragmatic and in line with uniswap ethos. Only risk is it means a bug in AM could lead to skimming but if we route it to the recoverer then that feels fine. (bug in AM will have other bad consequences for pricing & mint/burn anyway)

**Comment by xenide** [comment]
addressed in #172
