### ISSUE TITLE
question: why does solmate check if the `returndatasize` is greater than 31 bytes

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#159]
This is with reference to this [PR comment](https://github.com/vexchange/v3-core/pull/158#discussion_r1084366290). 

We know that solady does not check for this, and since we're using solady's impl at the time of writing, we need to know why solmate needs `returndatasize` to be greater than 31

**Comment by xenide** [comment]
Posed the question in the foundry group, but [answer](https://t.me/foundry_support/31847) was not satisfactory. 

Created an issue (question) on the repo itself [here](https://github.com/transmissions11/solmate/issues/361).

**Comment by OliverNChalk** [comment]
Just a heads up, returndata is expected to be abi-encoded. So impls that return uint8 will still return 32 bytes (it will be padded)

**Comment by xenide** [comment]
so as long as the function returns _something_, `gt(returndatasize(), 31)` will be true, correct?

**Comment by OliverNChalk** [comment]
for solidity yes
for evm no

afaik there is no way in solidity to return less than 32 bytes (apart from inline yul).

**Comment by xenide** [comment]
I propose to close this issue since vectorized has confirmed that it performs the [same checks](https://github.com/transmissions11/solmate/issues/361#issuecomment-1476718863) as well.

**Comment by xenide** [comment]
closing as agreed by @OliverNChalk
