### ISSUE TITLE
fix(`AaveManager`): handle WAVAX rewards on top of base rewards

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#161]
Currently the asset manager only tracks the shares of aave tokens each pair has. But we need a mechanism to handle the WAVAX rewards, and possibly to sell them and convert them into those aave tokens.

**Comment by xenide** [comment]
So, after considering the problem as a whole, this is my take on it: 

1. First problem we have to solve is, how do we attribute the amount of reward tokens for each pair 
   - e.g. Pair1 USDC-USDT has their USDC managed, Pair2 USDC-DAI also has their USDC managed, Pair3 BTC.b-STG has their BTC.b managed. All of them are entitled to an array of additional reward tokens, `[WAVAX, DOGE]`
   - how do we fairly / accurate distribute the rewards tokens to the `X` number of pairs having their same / diff tokens managed? 

2. Second problem we have to solve is, how do we sell those rewards into AaveTokens again, as this is what the asset manager holds anyway? 
   - integrate with an aggregator to dump reward tokens and receive corresponding AaveToken
      - this can be done in 1 step. 1inch supports swapping to the underlying and then going through AAVE to convert into the AaveToken. So we don't have to do an additional `supply`
      - perhaps we can refer to those yield aggregators like beefy / robo / autofarm to see how they execute this?
      - introduce a new function called `claimsAllRewardAndSellForAaveToken( aaveToken )`, make it an admin function 
   - if we can do this, then point 1 is no longer a problem, since the pie literally becomes bigger so everyone's shares are still valid 
   - one important thing to note is: we might have to do separate calls for different underlying tokens
      - e.g. AM has USDC and BTC.b in AAVE, both give WAVAX as additional rewards 
      - we need to make separate calls `claimsAllRewardAndSellForAaveToken(avUSDC)` + `claimsAllRewardAndSellForAaveToken(avBTC.b)` so that things are correctly accounted for 
   - a fallback solution would be: we go through AAVE governance to allow an external address to claim for the smart contract via `setClaimer`, see [proposal](https://governance.aave.com/t/arc-whitelist-balancer-s-liquidity-mining-claim/9724)
      - but I think we can implement a solution within the contract and not have to go through this

**Comment by OliverNChalk** [comment]
https://ethereum.org/en/developers/docs/standards/tokens/erc-4626/

We should have each pair deposit into a yield style vault so that they are rewarded per share. Then we no longer care of USDC came from USDC-USDT or USDC-AVAX

**Comment by xenide** [comment]
Okay, but our shares system (already implemented) can also achieve this, so we don't need to impl this exact standard do we? The key here is to dump whatever reward token into `avUSDC` and put it back to the AaveManager and we're good, since the balance is calculated this way:

`rTokenBalance = shares[aOwner][aToken] * ERC20(lAaveToken).balanceOf(address(this)) / lTotalShares;`

**Comment by OliverNChalk** [comment]
Yeah, I'm not familiar with our current asset manager but its fundamentally very achievable. We should only have 1 pool per asset and uses shares to track the ownership in the pool

**Comment by xenide** [comment]
Yup so that's already done. In terms of implementing the sale of the reward tokens, any thoughts? We should just plug it into 1inch if possible right?

**Comment by OliverNChalk** [comment]
Plugging into 1inch on chain is not possible, they provide off-chain api/quotes right?

**Comment by xenide** [comment]
so I asked in 1inch's discord, and it seems that the way to do it is: 

1. obtain the quote off-chain through their API. e.g. WAVAX -> USDC, calculate a reasonable slippage
2. perform a swap [like this](https://github.com/smye/1inch-swap/blob/master/contracts/SwapProxy.sol) using an `onlyOwner` `claimAndSwap` function. 
3. The owner will perform this function periodically 

I checked out paraswap's API as well and it seems pretty similar to 1inch's. Dunno if paraswap's docs are not up to date or what, but in the docs the list of networks don't include AVAX. It's prolly just not updated, cuz it obviously works on AVAX. So that's a potential candidate to route our swap through as well.

**Comment by OliverNChalk** [comment]
What about just using the same approach that I used for Vexchange (i.e. set trade size to a portion of pool value so it cannot be sandwiched). Then we can use our own pools

**Comment by xenide** [comment]
ah okay. So there's two cases we need to consider: 

1. the reward token for a particular market has a pool in our protocol
   - e.g. WAVAX reward for the USDC market -> we can convert it directly through the WAVAX-USDC pair
2. the reward token does not have a pool in our protocol 
   - then we have to swap it through an external protocol 

so when we build this `claimAndSwap` function, we need to be able to take care of these 2 situations, agree?

**Comment by OliverNChalk** [comment]
What reward tokens will we not have pools for? Like I'm imagining we launch with stable pools and a single volatile WAVAX-USDC pair?

**Comment by xenide** [comment]
right now the additional rewards only include WAVAX. But in the aave contracts, it can be programmed to be an array, so it would be prudent to think of and handle those situations

**Comment by OliverNChalk** [comment]
`GenericFactory.createPair(REWARD_ASSET, USDC)` is always possible, right? With 1inch we essentially are just saying, we trust an external user to sell the rewards on behalf of the AssetManager?

**Comment by OliverNChalk** [comment]
Perhaps the more technically challenging problem here, is how do we properly do accounting after a sale occurs. The sale mechanism is of less technical importance.

For instance if we allow an external user to manage the rewards, then we could simply have them sell periodically and the NAV would jump then. But what if users start frontrunning the sells because the LP NAV jumps only when we sell rewards?

I think this is fine in AssetManagerV1 because unlikely anyone is that sophisticated and we can take care to avoid mempools where possible

**Comment by xenide** [comment]
the NAV only gets updated when someone calls `mint` or `burn`, else the pair remains oblivious to the gains. And when `mint` / `burn` is called, all the LPs shares get updated anyway so I don't think this is a concern.


> `GenericFactory.createPair(REWARD_ASSET, USDC)` is always possible, right? With 1inch we essentially are just saying, we trust an external user to sell the rewards on behalf of the AssetManager?

but what if you have this scenario - WAVAX-BTC.b , with KKK as a reward token? Having a KKK-USDC pair doesn't sell it directly into WAVAX or BTC.b but I guess it does provide a route. So you propose to convert all rewards with our own pairs? And not rely on external protocols?

**Comment by OliverNChalk** [comment]
Two things:

1. If there is 100k USD of liquidity and 100k USD of unclaimed rewards, if a user calls mint they will add liquidity without triggering a reward sell. When the rewards are then sold they will get instant ROI and can burn with no LP risk.

2. As for only swapping through our own pairs, I think it makes sense. However, I think we should probably just build a role in the AssetManager called "RewardSeller" that can spend the rewards and report sale proceeds. Then the AM will handle distribution of these funds fairly (i.e. updating share price, or just routing the rewards correctly).

Problem 1 can be solved by claiming and selling rewards frequently enough and not using frontrunnable tx pools (private mempools), to start.

**Comment by xenide** [comment]
> 1. If there is 100k USD of liquidity and 100k USD of unclaimed rewards, if a user calls mint they will add liquidity without triggering a reward sell. When the rewards are then sold they will get instant ROI and can burn with no LP risk.
> Problem 1 can be solved by claiming and selling rewards frequently enough and not using frontrunnable tx pools (private mempools), to start.

Agreed. Ff we have scripts for this it has to be run periodically 

> 2. As for only swapping through our own pairs, I think it makes sense. However, I think we should probably just build a role in the AssetManager called "RewardSeller" that can spend the rewards and report sale proceeds. Then the AM will handle distribution of these funds fairly (i.e. updating share price, or just routing the rewards correctly).

the distribution of the converted rewards is not hard. We literally just have to convert from REWARD => aaveToken, e.g. `DOGE` => `a.USDC`. Since shares values are tracked by the aaveToken, we don't have to do more work for the calculation. Even if X number of pairs have `a.USDC` managed by the manager, the shares system takes care of it naturally

**Comment by OliverNChalk** [comment]
Makes sense

**Comment by xenide** [comment]
create a new role `RewardSeller` that can claim rewards through `AaveManager` and then is trusted to sell those rewards for respective aaveTokens
