### ISSUE TITLE
feat: set asset manager's owner behind a timelock

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#175]
Make sure the reservoir deployer sets up the asset manager owner behind a timelock

**Comment by xenide** [comment]
in terms of our options, the easiest would be to setup a timelock with openzeppelin's defender, and make that timelock the owner of the AssetManager. 

The factory and oracle caller should also be owned by this timelock right?  

If I'm not mistaken the OZ's defender can create a timelock that's deployed at the same address for all EVM chains

**Comment by OliverNChalk** [comment]
The asset manager is not scary, the factory that can set the asset manager is scary, right? The factory is able to call `setManager` on pairs
