### ISSUE TITLE
check: ensure StableMintBurn is still necessary

### ISSUE THREAD

**Issue by OliverNChalk** [vexchange/v3-core#178]
Make sure the code size hasn't dropped such that stable mint burn is no longer needed

**Comment by xenide** [comment]
So currently their bytecodes stand at around slightly less than 24K. 

I manually verified this by collapsing `StableMintBurn` into `StablePair`. The resultant bytecode size is 26180 bytes, which is still greater than 24576. So seems that we still need it for now

**Comment by OliverNChalk** [comment]
Let's leave this as part of final audit readiness checks
