### ISSUE TITLE
feat: support more granular fees

### ISSUE THREAD

**Issue by OliverNChalk** [vexchange/v3-core#36]
Most protocols let you set the fees down to the nearest basis point. It would be an advantage to be able to go more granular (so 1/10th of a basis point, particularly for stable swap pairs)

**Comment by xenide** [comment]
in my research it seems that curve has fees to the granularity of `1e-10` (0.000001 basis point) , albeit most of the fees are in the 4-50 basis points range. Saddle's is the same as curve, balancer's is to 0.01 basis point.  Synapse's fee is 1 basis point. 

So we still want to go ahead with this? 

What do you propose the resolution to be? The smallest we should support is 0.1 basis points? That should suffice right? On a $1M trade, the fees would be $10. Good enough?

**Comment by OliverNChalk** [comment]
Resolution isn't just about the minimum, it's about the ability to price/undercut other protocols. That said, I didn't realize cuve/saddle were so granular. I personally don't see a huge need in going beyond 0.1 BP. However, if we have spare capacity (before our maths starts to overflow) we could do 0.01 BP and then there would be no way we'd ever need more accuracy
