### ISSUE TITLE
feat: aligning / standardizing router interfaces for ConstantProductPair and StablePair

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#54]
As the two curves are forked from different sources, there is a need to refactor and align the interfaces for router smart contracts to interact with them in a uniform way

## Also to consider 
- interface to do flash swaps 

## Candidates 

1. uniswap v2 routers
   - addLiquidity, removeLiquidity, swapExactForToken, swapTokensForExact (as well as versions for the native token)
   - supports permit txs
   - getAmountOut / getAmountIn (and array versions)
   - supports feeOnTransfer tokens 
   - checks if slippage is too much
   - quote liquidity 
6. solidly 
   - addLiquidity / removeLiquidity, swapExactForToken, vice versa (as well as versions for native token)
   - supports permit txs
   - getAmountOut, getAmountsOut
   - quoteAddLiquidity
      - gives an estimate of how many LP tokens you'll get by providing a certain amt of liquidity 
   - quoteRemoveLiquidity 
      - gives an estimate of how much underlying tokens you can redeem by providing a certain amount of LP tokens
   - inspired from uni v2 router, very similar 
2. uniswap v3 routers
   - exactOutput, exactOutputSingle, exactInput, exactInputSingle
   - checks if slippage is too much  
   - seems like it is possible to do multi-path, need to validate
4. sushi trident 
   - add / burn liquidity, add / burn liquidity single (should be equiv to a swap after redeem)
   - seems to support permit txs
   - exactInput, exactInputSingle, complexPath
   - don't have methods that do exact output 
   - deployPool
   - seems to be inspired by uniswap v3's routers 
   - **can do multi-path with with multiple input tokens, diff percentages for each path, multiple output tokens**
   - checks slippage 
5. balancer
   - off chain router, called smart order router (SOR) 
   - takes gas into account, will only split routes / hop multiple times only if it is more economical overall 
   - written in ts
   - supports multi route + multi hop 

## Our approach 

- liquidity methods to expose
   - addLiquidity, addLiquiditySingle
   - removeLiquidity, removeLiquiditySingle
   - do we want to support txs with permits? 
- swap methods to expose
   - multipath, multiple input tokens, single output token <= too ambitious?
   - how do we want to support native tokens? 
      - univ2 approach: swap methods take care of wrapping + unwrapping
      - univ3 approach: assume all tokens are wrapped and do a batch call to `unwrapWETH` if desired. To be controlled by the frontend 
- query methods 
   - getAmountOut(pair, curveId, tokenIn, amountIn) 
   - quoteAddLiquidity 
   - quoteRemoveLiquidity
      - let people see how much they can get if they burn a certain amount of LP tokens

**Comment by xenide** [comment]
> Some points:
> 
> * All projects have an "off-chain" router. The on-chain contract is merely the executor of the optimal path (which is calculated off-chain). I don't think any protocols calculate the optimal path on-chain due to gas constraints?

Yes you're right. 


> * **Do we want `addLiquiditySingle`? I** know this is popular for stable pairs but it seems quite dangerous for volatile pairs?
>   
>   * One way to offer this is we could provide `multicall` functionality. Then UIs can simply call `[swap(a, b), addLiquidity(a, b)]`? This seems cleaner and more composable, like the only downside is if our pairs expose addLiqOne, then its gas optimal to make a single call using that. But i dont think our pairs should expose addLiqOne - seems like feature creep.

Agree that we `addLiqOne` should not be a core pair function, and only be in the router. We can achieve this with UniV3's `multicall` [library](https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/Multicall.sol). 

Doing this via the UI seems risky cuz price can change quite a bit in between the two transactions. 

Okay so we agree that we need `addLiquiditySingle` + `removeLiquiditySingle` function in the router yes? 

> * `do we want to support txs with permits`, **this doesn't need to be done at the pair level right**? This can be done at the router if users are approving routers.

I think you're right. UniV3 supports this in the router but UniV2 supports this in both the router and the pair itself. 

For V2's pair+router, the permit is for the LP token itself (not super useful). For V3 they don't hold ERC20 LP tokens, so the permit is for the underlying tokens. 

So we DO want to support it in the router yeah? 

> * Multi input => again, **just use multi-call**, building the routing logic for this will be non trivial and something we wanna do later/iterate over time.

okay not priority for now, will consider in the future 

> * I like the **batch call approach for wrap/unwrap**, simpler and more composable.

okay then it seems like we'll be using the `multicall` lib anyway. Here's an [example](https://github.com/Uniswap/v3-periphery/blob/5bcdd9f67f9394f3159dad80d0dd01d37ca08c66/test/SwapRouter.spec.ts#L748) of how to call it 

> * Query methods are good

alright good. 

> ## BTW
> How do we want to align the interfaces of the stable and volatile pool?

Yes this is related to the asset manager inheritance problem we have. I'll come up with a proposal soon. 



In terms of the swap interface, we want: 

single input => single / multiple hops => single output. Agree?

**Comment by OliverNChalk** [comment]
> Okay so we agree that we need addLiquiditySingle + removeLiquiditySingle function in the router yes?

Please add them as optional features to the router, like a nice to have. Not blocking audit.

> I think you're right. UniV3 supports this in the router but UniV2 supports this in both the router and the pair itself.

I don't think the pair supports anything via permit? However, the pair is itself an ERC-20 and thus implements permit.

> So we DO want to support it in the router yeah?

Yeah, I was very surprised they didn't support swapping with permit. We should strive to add it.

> single input => single / multiple hops => single output. Agree?

Yes

**Comment by xenide** [comment]
Closing as they are addressed in #77 and in [this issue](https://github.com/vexchange/v3-periphery/pull/1)
