### ISSUE TITLE
test(oracle): prove that uint112 for accLogPrice and accLogLiq cannot overflow before the timestamp

### ISSUE THREAD

**Issue by xenide** [vexchange/v3-core#68]
Write invariants that prove the above

**Comment by xenide** [comment]
actually, since we're allowing all 3 to overflow, does it matter if `accLogPrice` or `accLogLiq` overflows before `timestamp`? @OliverNChalk

**Comment by OliverNChalk** [comment]
Uhh, we just want to know what's the quickest accLogPrice could overflow. E.g. overflows are fine as long as its not an overflow between trades. E.g. t0 = 100 ..... overflow ..... t1 = 110

**Comment by xenide** [comment]
Given that we already have [the math & documentation](https://github.com/vexchange/v3-core/blob/cb7481fb6d12726f3872fc1d7afc916335382ff6/src/interfaces/IOracleWriter.sol#L6) that the accumulator would not overflow before the timestamp, is this still necessary?  

I'm leaning towards no. Also since we already have the docs for `logAccClampedPrice` which is an `int56`, it would also imply that the `logAccRawPrice` would not overflow too since it's a bigger type at `int112`, so we don't have to duplicate the docs.

**Comment by OliverNChalk** [comment]
Sounds reasonable
